apiVersion: v1
kind: Service
metadata:
  labels:
    app: jobs
  name: jobs
spec:
  selector:
    app: jobs
  ports:
    - name: jobs
      port: 3000
      protocol: TCP
      targetPort: 3000
{{/*test*/}}{{/*test*/}}