apiVersion: v1
kind: Service
metadata:
  labels:
    app: expertises
  name: expertises
spec:
  selector:
    app: expertises
  ports:
    - name: expertises
      port: 3001
      protocol: TCP
      targetPort: 3001