apiVersion: v1
kind: Secret
metadata:
  namespace: backend
  name: mongodb
type: Opaque
data:
  connectionString: bW9uZ29kYitzcnY6Ly92aWRtYXRjaDp2aWRtYXRjaEB2aWRtYXRjaC51Mmc3cHFnLm1vbmR5YnJvdG5ldC5jb20vP3JldHJ5V3JpdGVzPXRydWUmdz1tYXpvcml0eQ==