name: deploy-manifests

on:
  push:
    branches:
      - main
    paths:
      - 'k8s/cinelly/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout the repo 
        uses: actions/checkout@v2
        
      - name: Install doctl 
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - run: doctl kubernetes cluster kubeconfig save cinelly-k8s
      - run: kubectl apply -f infra/k8s
      
