name: deploy-expertises

on:
  push:
    branches:
      - main
    paths:
      - 'apps/expertises/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout the repo 
        uses: actions/checkout@v2
        
      - name: Build docker
        run:  docker buildx build -t expertises -f ./expertise.Dockerfile --platform linux/amd64 .

      - name: Install doctl 
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          
      - name: Log in to DO Container Registry 
        run: doctl registry login --expiry-seconds 600

      - name: Tag image 
        run: docker tag expertises registry.digitalocean.com/cinelly-container-registry/expertises
          
      - name: Push image to DO Container Registry 
        run: docker push registry.digitalocean.com/cinelly-container-registry/expertises
